spring:
  #配置数据源
  datasource:
    #公共属性
    name: productDruid
    username: root
    password: GDUTmall-2020
    url: jdbc:mysql://localhost:3306/secondhandmall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #Druid特有属性
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0ms
  mvc:
    static-path-pattern: /static/image/**
  resources:
    static-locations: file:/project/

server:
  port: 8080

elasticsearch:
  address: localhost

picture:
  path: /project

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0

mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.gdut.secondhandmall.Do
  configuration:
    map-underscore-to-camel-case: true
